# Generated by Django 5.1.5 on 2025-01-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50, unique=True)),
                ('city', models.CharField(default='Moscow', max_length=100)),
                ('notification_time', models.TimeField(default='08:00')),
            ],
        ),
    ]
