# Generated by Django 5.1.5 on 2025-02-03 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'Настройка пользователя', 'verbose_name_plural': 'Настройки пользователей'},
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='chat_id',
            field=models.BigIntegerField(unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='city',
            field=models.CharField(default='Moscow', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='notification_time',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Время уведомлений'),
        ),
    ]
