# Generated by Django 5.1.5 on 2025-02-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_bot', '0002_alter_usersettings_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={},
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='chat_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='city',
            field=models.CharField(default='Moscow', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='notification_time',
            field=models.TimeField(default='08:00'),
        ),
    ]
